const { it } = require("mocha");
describe('Visit Swag labs', () => {
  beforeEach(function(){
    cy.visit('https://www.saucedemo.com/')
})
  it('[1] Login', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
  })
  it('[2] Login1', () => {
    cy.username().type("locked_out_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get(['.error-button'])
  })
  it('[3] Login2', () => {
    cy.username().type("problem_user")
    cy.password().type("secret_sauce")
    cy.Login()
  })
  it('[4] Login3', () => {
    cy.username().type("performance_glitch_user")
    cy.password().type("secret_sauce")
    cy.Login()
  })
  it('[5] Login4', () => {
    cy.username().type("error_user")
    cy.password().type("secret_sauce")
    cy.Login()
  })
  it('[6] Login5', () => {
    cy.visit('https://www.saucedemo.com/')
    cy.username().type("visual_user")
    cy.password().type("secret_sauce")
    cy.Login()
  })
  it('[7] invalid Username', () => {
    cy.username().type("Ayman")
    cy.password().type("secret_sauce")
    cy.Login()
  })
  it('[8] invalid password', () => {
    cy.visit('https://www.saucedemo.com/')
    cy.username().type("visual_user")
    cy.password().type("hello")
    cy.Login()
  })
  it('[9] click item', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
  })
  it('[10] Add to cart', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get ('[name="add-to-cart"]') .eq (0).click()
  })
  it('[11] remove from cart', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get ('[name="add-to-cart"]') .eq (0).click()
    cy.get ('[name="remove"]') .eq (0).click()
  })
  it('[12] click the filter', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get('.product_sort_container').select("az")
  })
  it('[12] click the filter', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get('.product_sort_container').select("za")
  })
  it('[13] click the filter', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get('.product_sort_container').select("lohi")
  })
  it('[14] click the filter', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get('.product_sort_container').select("hilo")
  })
  it('[15] Add to cart', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get ('[name="add-to-cart"]') .eq (0).click()
    cy.get('.shopping_cart_container').click()
  })
  it('[16] Checkout', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get ('[name="add-to-cart"]') .eq (0).click()
    cy.get('.shopping_cart_container').click()
    cy.get('[name="checkout"]').click()
  })
  it('[17] continue shopping', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get ('[name="add-to-cart"]') .eq (0).click()
    cy.get('.shopping_cart_container').click()
    cy.get('[name="continue-shopping"]').click()
  })
  it('[18] Checkout1', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get ('[name="add-to-cart"]') .eq (0).click()
    cy.get('.shopping_cart_container').click()
    cy.get('[name="checkout"]').click()
    cy.get('.form_group').eq(0).type('Ayman')
    cy.get('[name="continue"]').click()
  })
  it('[19] Checkout2', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get ('[name="add-to-cart"]') .eq (0).click()
    cy.get('.shopping_cart_container').click()
    cy.get('[name="checkout"]').click()
    cy.get('.form_group').eq(1).type('Ragab')
    cy.get('[name="continue"]').click()
  })
  it('[20] Checkout2', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get ('[name="add-to-cart"]') .eq (0).click()
    cy.get('.shopping_cart_container').click()
    cy.get('[name="checkout"]').click()
    cy.get('.form_group').eq(2).type('1565')
    cy.get('[name="continue"]').click()
  })
  it('[21] Checkout2', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get ('[name="add-to-cart"]') .eq (0).click()
    cy.get('.shopping_cart_container').click()
    cy.get('[name="checkout"]').click()
    cy.get('.form_group').eq(0).type('Ayman')
    cy.get('.form_group').eq(1).type('Ragab')
    cy.get('.form_group').eq(2).type('1565')
    cy.get('[name="continue"]').click()
  })
  it.only('[22] Overview', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get ('[name="add-to-cart"]') .eq (0).click()
    cy.get('.shopping_cart_container').click()
    cy.get('[name="checkout"]').click()
    cy.get('.form_group').eq(0).type('Ayman')
    cy.get('.form_group').eq(1).type('Ragab')
    cy.get('.form_group').eq(2).type('1565')
    cy.get('[name="continue"]').click()
    cy.get('[name="finish"]')
  })
  it('[22] Overview', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get ('[name="add-to-cart"]') .eq (0).click()
    cy.get('.shopping_cart_container').click()
    cy.get('[name="checkout"]').click()
    cy.get('.form_group').eq(0).type('Ayman')
    cy.get('.form_group').eq(1).type('Ragab')
    cy.get('.form_group').eq(2).type('1565')
    cy.get('[name="continue"]').click()
    cy.get('[name="cancel"]')
  })
  it('[23] Menu', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get('.bm-burger-button').click()
  })
  it('[24] Menu', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get('.bm-burger-button').click()
    cy.get('.bm-item.menu-item').eq(1).click()
  })
  it('[24] Menu', () => {
    cy.username().type("standard_user")
    cy.password().type("secret_sauce")
    cy.Login()
    cy.get ('.inventory_item_img') .eq (0).click()
    cy.get('.bm-burger-button').click()
    cy.get('.bm-item.menu-item').eq(2).click()
  })
})